---
- import_tasks: packages.yaml
  tags: packages
- import_tasks: git.yaml
  tags: git
- import_tasks: fish.yaml
  tags: fish
- import_tasks: kitty.yaml
  tags: kitty
- import_tasks: amazonq.yaml
  tags: amazonq